Update patch set 1
Patch Set 1:

???
TypeError: an integer is required
FATAL ERROR: python callback <bound method RPMTransaction.callback of <yum.rpmtrans.RPMTransaction instance at 0x28d0488>> failed, aborting!

Patch-set: 1
Reviewer: Gerrit User 85 <85@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0